### ISSUE TITLE
Figure out what to do with map/galleries section

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#100]
Can we just add a list of all the galleries and their addresses/shows?

If there is time we can add more actual functionality in the future.

**Comment by alexjacque** [comment]
I did a quick mockup of how the list of galleries with pin icons could work. The width metrics aren't right so that'd need to be massaged when actually being put in use, but it's a start at least. [https://github.com/alexjacque/mgs/tree/master/pin_demo](https://github.com/alexjacque/mgs/tree/master/pin_demo)
