### ISSUE TITLE
Need to put the fontface fonts somewhere else...

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#120]
Idiot move — webfont files are all just available in the repo, font designer doesn't like it and has asked us to remove them — I guess I could supersimple them?

**Comment by alexjacque** [comment]
Should perhaps the repo the made private? Or would that not work for whatever reason (hit the limit for private repos, not jive with whatever backend things you have hooked up to this repo, etc)?

**Comment by bjornmeansbear** [comment]
We've moved them so they aren't in the main repo now. Just need to figure out how to retroactively get rid of them in the old branches/commits if possible.

**Comment by bjornmeansbear** [comment]
@alexjacque kai and I setup a separate server that follows all of the requested things in the licensing agreement, only the micagradshow.com website can access them there... so that's solved.

**Comment by bjornmeansbear** [comment]
mostly solved by ca1b1297e303617dd1a6619281a9fb62eb5316d6

**Comment by alexjacque** [comment]
I had some success with the [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) before when removing some files that contained sensitive data. I was somewhat uncertain if I was doing things right when trying to follow along with the directions, but then again I was (and still am) a Git noob, so that probably factored into it.

**Comment by bjornmeansbear** [comment]
@webmasterkai can you use your knowledge and power to make sure the font-face fonts get wiped out from the old commits?
